# dnf tasks file for sjpbeale.mongodb

- name: "Check version valid"
  uri:
    url: https://repo.mongodb.org/yum/redhat/7/mongodb-org/{{ mongodb_version }}/x86_64/
    return_content: yes
  register: http_response
  failed_when: http_response.status != 200
  run_once: true

- name: "Ensure repo present"
  sudo: yes
  template:
    src: mongo.repo.j2
    dest: /etc/yum.repos.d/mongodb-org-{{ mongodb_version }}.repo
    owner: root
    group: root
    mode: 0644

- name: "Ensure installed"
  sudo: yes
  dnf: name=mongodb-org

- name: "Start service"
  service: name=mongod state=started enabled=true
