---
# tasks file for sjpbeale.skype

- name: "Ensure Skype repo present"
  sudo: yes
  copy: src=skype.repo
        dest=/etc/yum.repos.d/
        owner=root group=root mode=0644

- name: "Ensure Skype present"
  sudo: yes
  dnf: name=skypeforlinux
